import { Exercise } from './types';

export function seedExercises(): Exercise[] {
  return [
    // ── CHEST (Push) ──
    {
      id: 'push_up',
      name: 'Push-Up',
      equipment: ['bodyweight'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['triceps', 'shoulders'],
      movementPattern: 'push',
      difficultyTier: 1,
      instructions: 'Hands shoulder-width, lower chest to floor, press up. Keep core tight and body in a straight line.',
      harderSubstitution: 'diamond_push_up',
    },
    {
      id: 'diamond_push_up',
      name: 'Diamond Push-Up',
      equipment: ['bodyweight'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['triceps'],
      movementPattern: 'push',
      difficultyTier: 3,
      instructions: 'Hands together forming a diamond under chest. Lower and press up.',
      easierSubstitution: 'push_up',
      harderSubstitution: 'archer_push_up',
    },
    {
      id: 'archer_push_up',
      name: 'Archer Push-Up',
      equipment: ['bodyweight'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['triceps', 'shoulders'],
      movementPattern: 'push',
      difficultyTier: 4,
      instructions: 'Wide hand placement. Shift weight to one arm as you lower, keeping the other arm straight.',
      easierSubstitution: 'diamond_push_up',
    },
    {
      id: 'db_bench_press',
      name: 'Dumbbell Bench Press',
      equipment: ['dumbbells', 'bench'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['triceps', 'shoulders'],
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Lie on bench, press dumbbells up from chest level. Lower with control.',
      harderSubstitution: 'db_incline_press',
    },
    {
      id: 'db_floor_press',
      name: 'Dumbbell Floor Press',
      equipment: ['dumbbells'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['triceps'],
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Lie on floor, press dumbbells up. Elbows touch floor at bottom.',
      harderSubstitution: 'db_bench_press',
    },
    {
      id: 'db_incline_press',
      name: 'Dumbbell Incline Press',
      equipment: ['dumbbells', 'bench'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['shoulders', 'triceps'],
      movementPattern: 'push',
      difficultyTier: 3,
      instructions: 'Bench at 30-45°. Press dumbbells from upper chest. Control the descent.',
      easierSubstitution: 'db_bench_press',
    },
    {
      id: 'band_chest_press',
      name: 'Band Chest Press',
      equipment: ['resistance_bands'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['triceps', 'shoulders'],
      movementPattern: 'push',
      difficultyTier: 1,
      instructions: 'Anchor band behind you at chest height. Press forward, extending arms fully.',
      harderSubstitution: 'band_chest_fly',
    },
    {
      id: 'band_chest_fly',
      name: 'Band Chest Fly',
      equipment: ['resistance_bands'],
      primaryMuscle: 'chest',
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Anchor band behind you. Arms slightly bent, bring hands together in front of chest.',
      easierSubstitution: 'band_chest_press',
    },

    // ── BACK (Pull) ──
    {
      id: 'inverted_row',
      name: 'Inverted Row (Table)',
      equipment: ['bodyweight'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 1,
      instructions: 'Lie under a sturdy table, grip edge, pull chest to table. Keep body straight.',
      harderSubstitution: 'pull_up',
    },
    {
      id: 'towel_row',
      name: 'Towel Row',
      equipment: ['bodyweight'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 1,
      instructions: 'Loop a towel around a door handle or pole. Lean back and row yourself in.',
      harderSubstitution: 'pull_up',
    },
    {
      id: 'pull_up',
      name: 'Pull-Up',
      equipment: ['pull_up_bar'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 4,
      instructions: 'Hang from bar, pull chin above bar. Control the descent.',
      easierSubstitution: 'inverted_row',
      harderSubstitution: 'weighted_pull_up',
    },
    {
      id: 'weighted_pull_up',
      name: 'Weighted Pull-Up',
      equipment: ['pull_up_bar'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 5,
      instructions: 'Perform a pull-up with added weight (backpack, belt).',
      easierSubstitution: 'pull_up',
    },
    {
      id: 'db_row',
      name: 'Dumbbell Row',
      equipment: ['dumbbells'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 2,
      instructions: 'Hinge at hips, one hand on support. Row dumbbell to hip, squeeze shoulder blade.',
      harderSubstitution: 'db_bent_over_row',
    },
    {
      id: 'db_bent_over_row',
      name: 'Dumbbell Bent-Over Row',
      equipment: ['dumbbells'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 3,
      instructions: 'Hinge forward 45°, row both dumbbells simultaneously to hips.',
      easierSubstitution: 'db_row',
    },
    {
      id: 'band_row',
      name: 'Band Row',
      equipment: ['resistance_bands'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 1,
      instructions: 'Anchor band at waist height. Pull handles to sides, squeezing shoulder blades.',
      harderSubstitution: 'band_face_pull',
    },
    {
      id: 'band_face_pull',
      name: 'Band Face Pull',
      equipment: ['resistance_bands'],
      primaryMuscle: 'back',
      secondaryMuscles: ['shoulders'],
      movementPattern: 'pull',
      difficultyTier: 2,
      instructions: 'Anchor band at face height. Pull to face, rotating hands outward. Squeeze rear delts.',
      easierSubstitution: 'band_row',
    },
    {
      id: 'band_pull_apart',
      name: 'Band Pull-Apart',
      equipment: ['resistance_bands'],
      primaryMuscle: 'back',
      secondaryMuscles: ['shoulders'],
      movementPattern: 'pull',
      difficultyTier: 1,
      instructions: 'Hold band at shoulder width, arms extended. Pull apart until band touches chest.',
    },

    // ── SHOULDERS ──
    {
      id: 'pike_push_up',
      name: 'Pike Push-Up',
      equipment: ['bodyweight'],
      primaryMuscle: 'shoulders',
      secondaryMuscles: ['triceps'],
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Hips high in an inverted V. Bend elbows to lower head toward floor, then press up.',
      easierSubstitution: 'push_up',
      harderSubstitution: 'decline_pike_push_up',
    },
    {
      id: 'decline_pike_push_up',
      name: 'Decline Pike Push-Up',
      equipment: ['bodyweight'],
      primaryMuscle: 'shoulders',
      secondaryMuscles: ['triceps'],
      movementPattern: 'push',
      difficultyTier: 3,
      instructions: 'Feet elevated on chair. Pike position. Lower head toward floor and press up.',
      easierSubstitution: 'pike_push_up',
    },
    {
      id: 'db_shoulder_press',
      name: 'Dumbbell Shoulder Press',
      equipment: ['dumbbells'],
      primaryMuscle: 'shoulders',
      secondaryMuscles: ['triceps'],
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Seated or standing, press dumbbells overhead from shoulder height.',
      harderSubstitution: 'db_arnold_press',
    },
    {
      id: 'db_arnold_press',
      name: 'Arnold Press',
      equipment: ['dumbbells'],
      primaryMuscle: 'shoulders',
      secondaryMuscles: ['triceps'],
      movementPattern: 'push',
      difficultyTier: 3,
      instructions: 'Start with palms facing you. Rotate palms outward as you press overhead.',
      easierSubstitution: 'db_shoulder_press',
    },
    {
      id: 'db_lateral_raise',
      name: 'Dumbbell Lateral Raise',
      equipment: ['dumbbells'],
      primaryMuscle: 'shoulders',
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Arms at sides, raise dumbbells out to shoulder height. Slight bend in elbows.',
    },
    {
      id: 'band_shoulder_press',
      name: 'Band Shoulder Press',
      equipment: ['resistance_bands'],
      primaryMuscle: 'shoulders',
      secondaryMuscles: ['triceps'],
      movementPattern: 'push',
      difficultyTier: 1,
      instructions: 'Stand on band, press handles overhead. Control the return.',
    },

    // ── ARMS ──
    {
      id: 'db_bicep_curl',
      name: 'Dumbbell Bicep Curl',
      equipment: ['dumbbells'],
      primaryMuscle: 'biceps',
      movementPattern: 'pull',
      difficultyTier: 1,
      instructions: 'Stand with dumbbells at sides. Curl to shoulders, lower with control.',
      harderSubstitution: 'db_hammer_curl',
    },
    {
      id: 'db_hammer_curl',
      name: 'Dumbbell Hammer Curl',
      equipment: ['dumbbells'],
      primaryMuscle: 'biceps',
      movementPattern: 'pull',
      difficultyTier: 2,
      instructions: 'Palms facing each other. Curl dumbbells to shoulders.',
      easierSubstitution: 'db_bicep_curl',
    },
    {
      id: 'band_bicep_curl',
      name: 'Band Bicep Curl',
      equipment: ['resistance_bands'],
      primaryMuscle: 'biceps',
      movementPattern: 'pull',
      difficultyTier: 1,
      instructions: 'Stand on band, curl handles to shoulders. Keep elbows at sides.',
    },
    {
      id: 'tricep_dip',
      name: 'Tricep Dip (Chair)',
      equipment: ['bodyweight'],
      primaryMuscle: 'triceps',
      secondaryMuscles: ['chest', 'shoulders'],
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Hands on chair edge behind you, lower body by bending elbows to 90°, press up.',
      easierSubstitution: 'push_up',
    },
    {
      id: 'db_tricep_extension',
      name: 'Dumbbell Tricep Extension',
      equipment: ['dumbbells'],
      primaryMuscle: 'triceps',
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Hold one dumbbell overhead with both hands. Lower behind head, extend up.',
    },
    {
      id: 'band_tricep_pushdown',
      name: 'Band Tricep Pushdown',
      equipment: ['resistance_bands'],
      primaryMuscle: 'triceps',
      movementPattern: 'push',
      difficultyTier: 1,
      instructions: 'Anchor band above. Push handles down, extending elbows fully. Keep elbows at sides.',
    },

    // ── LEGS ──
    {
      id: 'bodyweight_squat',
      name: 'Bodyweight Squat',
      equipment: ['bodyweight'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes'],
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'Feet shoulder-width. Sit back and down, thighs parallel. Drive up through heels.',
      harderSubstitution: 'jump_squat',
    },
    {
      id: 'jump_squat',
      name: 'Jump Squat',
      equipment: ['bodyweight'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes', 'calves'],
      movementPattern: 'legs',
      difficultyTier: 3,
      instructions: 'Squat down, then explode upward. Land softly and immediately descend again.',
      easierSubstitution: 'bodyweight_squat',
    },
    {
      id: 'goblet_squat',
      name: 'Goblet Squat',
      equipment: ['dumbbells'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes', 'core'],
      movementPattern: 'legs',
      difficultyTier: 2,
      instructions: 'Hold dumbbell at chest. Squat deep, elbows between knees. Drive up.',
      easierSubstitution: 'bodyweight_squat',
    },
    {
      id: 'band_squat',
      name: 'Band Squat',
      equipment: ['resistance_bands'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes'],
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'Stand on band, hold handles at shoulders. Squat and stand.',
    },
    {
      id: 'forward_lunge',
      name: 'Forward Lunge',
      equipment: ['bodyweight'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes', 'hamstrings'],
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'Step forward, lower back knee toward floor. Push back to start. Alternate legs.',
      harderSubstitution: 'bulgarian_split_squat',
    },
    {
      id: 'bulgarian_split_squat',
      name: 'Bulgarian Split Squat',
      equipment: ['bodyweight'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes'],
      movementPattern: 'legs',
      difficultyTier: 3,
      instructions: 'Rear foot elevated on bench/chair. Lower until front thigh is parallel. Drive up.',
      easierSubstitution: 'forward_lunge',
    },
    {
      id: 'db_lunge',
      name: 'Dumbbell Lunge',
      equipment: ['dumbbells'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes', 'hamstrings'],
      movementPattern: 'legs',
      difficultyTier: 2,
      instructions: 'Hold dumbbells at sides. Step forward into lunge, alternate legs.',
      easierSubstitution: 'forward_lunge',
    },
    {
      id: 'glute_bridge',
      name: 'Glute Bridge',
      equipment: ['bodyweight'],
      primaryMuscle: 'glutes',
      secondaryMuscles: ['hamstrings'],
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'Lie on back, feet flat. Drive hips up, squeeze glutes at top. Lower with control.',
      harderSubstitution: 'single_leg_glute_bridge',
    },
    {
      id: 'single_leg_glute_bridge',
      name: 'Single-Leg Glute Bridge',
      equipment: ['bodyweight'],
      primaryMuscle: 'glutes',
      secondaryMuscles: ['hamstrings'],
      movementPattern: 'legs',
      difficultyTier: 3,
      instructions: 'One leg extended. Drive hips up on the planted foot. Squeeze at top.',
      easierSubstitution: 'glute_bridge',
    },
    {
      id: 'db_rdl',
      name: 'Dumbbell Romanian Deadlift',
      equipment: ['dumbbells'],
      primaryMuscle: 'hamstrings',
      secondaryMuscles: ['glutes', 'back'],
      movementPattern: 'legs',
      difficultyTier: 2,
      instructions: 'Hold dumbbells, hinge at hips pushing hips back. Slight knee bend. Feel hamstring stretch.',
    },
    {
      id: 'nordic_curl_negative',
      name: 'Nordic Curl (Negative)',
      equipment: ['bodyweight'],
      primaryMuscle: 'hamstrings',
      movementPattern: 'legs',
      difficultyTier: 4,
      instructions: 'Kneel with feet anchored. Slowly lower body forward using hamstrings. Push back up from floor.',
      easierSubstitution: 'glute_bridge',
    },
    {
      id: 'calf_raise',
      name: 'Calf Raise',
      equipment: ['bodyweight'],
      primaryMuscle: 'calves',
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'Stand on edge of step. Rise up on toes, lower heels below step level.',
    },
    {
      id: 'db_calf_raise',
      name: 'Dumbbell Calf Raise',
      equipment: ['dumbbells'],
      primaryMuscle: 'calves',
      movementPattern: 'legs',
      difficultyTier: 2,
      instructions: 'Hold dumbbells at sides. Rise up on toes, pause, lower slowly.',
      easierSubstitution: 'calf_raise',
    },

    // ── CORE ──
    {
      id: 'plank',
      name: 'Plank',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 1,
      instructions: 'Forearms on floor, body straight from head to heels. Hold position. Breathe steadily.',
      harderSubstitution: 'plank_shoulder_tap',
    },
    {
      id: 'plank_shoulder_tap',
      name: 'Plank Shoulder Tap',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 2,
      instructions: 'High plank. Tap opposite shoulder with each hand, minimizing hip rotation.',
      easierSubstitution: 'plank',
    },
    {
      id: 'dead_bug',
      name: 'Dead Bug',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 1,
      instructions: 'Lie on back, arms up, knees at 90°. Extend opposite arm and leg. Keep lower back pressed down.',
    },
    {
      id: 'mountain_climber',
      name: 'Mountain Climber',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      secondaryMuscles: ['shoulders'],
      movementPattern: 'core',
      difficultyTier: 2,
      instructions: 'High plank. Drive knees to chest alternately at a brisk pace.',
    },
    {
      id: 'bicycle_crunch',
      name: 'Bicycle Crunch',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 2,
      instructions: 'Lie on back, hands behind head. Rotate elbow to opposite knee, alternating sides.',
    },
    {
      id: 'russian_twist',
      name: 'Russian Twist',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 2,
      instructions: 'Seated, lean back slightly, feet off floor. Rotate torso side to side.',
      harderSubstitution: 'db_russian_twist',
    },
    {
      id: 'db_russian_twist',
      name: 'Dumbbell Russian Twist',
      equipment: ['dumbbells'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 3,
      instructions: 'Same as Russian Twist but holding a dumbbell for added resistance.',
      easierSubstitution: 'russian_twist',
    },
    {
      id: 'leg_raise',
      name: 'Leg Raise',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 2,
      instructions: 'Lie on back, legs straight. Raise legs to 90° then lower slowly. Keep lower back flat.',
    },
  ];
}
