import { Exercise } from './types';

export function seedExercises(): Exercise[] {
  return [
    // ── CHEST (Push) ──
    {
      id: 'push_up',
      name: 'Push-Up',
      equipment: ['bodyweight'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['triceps', 'shoulders'],
      movementPattern: 'push',
      difficultyTier: 1,
      instructions: 'Hands shoulder-width, lower chest to floor, press up. Keep core tight and body in a straight line.',
      harderSubstitution: 'diamond_push_up',
    },
    {
      id: 'diamond_push_up',
      name: 'Diamond Push-Up',
      equipment: ['bodyweight'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['triceps'],
      movementPattern: 'push',
      difficultyTier: 3,
      instructions: 'Hands together forming a diamond under chest. Lower and press up.',
      easierSubstitution: 'push_up',
      harderSubstitution: 'archer_push_up',
    },
    {
      id: 'archer_push_up',
      name: 'Archer Push-Up',
      equipment: ['bodyweight'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['triceps', 'shoulders'],
      movementPattern: 'push',
      difficultyTier: 4,
      instructions: 'Wide hand placement. Shift weight to one arm as you lower, keeping the other arm straight.',
      easierSubstitution: 'diamond_push_up',
    },
    {
      id: 'db_bench_press',
      name: 'Dumbbell Bench Press',
      equipment: ['dumbbells', 'bench'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['triceps', 'shoulders'],
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Lie on bench, press dumbbells up from chest level. Lower with control.',
      harderSubstitution: 'db_incline_press',
    },
    {
      id: 'db_floor_press',
      name: 'Dumbbell Floor Press',
      equipment: ['dumbbells'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['triceps'],
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Lie on floor, press dumbbells up. Elbows touch floor at bottom.',
      harderSubstitution: 'db_bench_press',
    },
    {
      id: 'db_incline_press',
      name: 'Dumbbell Incline Press',
      equipment: ['dumbbells', 'bench'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['shoulders', 'triceps'],
      movementPattern: 'push',
      difficultyTier: 3,
      instructions: 'Bench at 30-45°. Press dumbbells from upper chest. Control the descent.',
      easierSubstitution: 'db_bench_press',
    },
    {
      id: 'band_chest_press',
      name: 'Band Chest Press',
      equipment: ['resistance_bands'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['triceps', 'shoulders'],
      movementPattern: 'push',
      difficultyTier: 1,
      instructions: 'Anchor band behind you at chest height. Press forward, extending arms fully.',
      harderSubstitution: 'band_chest_fly',
    },
    {
      id: 'band_chest_fly',
      name: 'Band Chest Fly',
      equipment: ['resistance_bands'],
      primaryMuscle: 'chest',
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Anchor band behind you. Arms slightly bent, bring hands together in front of chest.',
      easierSubstitution: 'band_chest_press',
    },

    // ── BACK (Pull) ──
    {
      id: 'inverted_row',
      name: 'Inverted Row (Table)',
      equipment: ['bodyweight'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 1,
      instructions: 'Lie under a sturdy table, grip edge, pull chest to table. Keep body straight.',
      harderSubstitution: 'pull_up',
    },
    {
      id: 'towel_row',
      name: 'Towel Row',
      equipment: ['bodyweight'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 1,
      instructions: 'Loop a towel around a door handle or pole. Lean back and row yourself in.',
      harderSubstitution: 'pull_up',
    },
    {
      id: 'pull_up',
      name: 'Pull-Up',
      equipment: ['pull_up_bar'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 4,
      instructions: 'Hang from bar, pull chin above bar. Control the descent.',
      easierSubstitution: 'inverted_row',
      harderSubstitution: 'weighted_pull_up',
    },
    {
      id: 'weighted_pull_up',
      name: 'Weighted Pull-Up',
      equipment: ['pull_up_bar'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 5,
      instructions: 'Perform a pull-up with added weight (backpack, belt).',
      easierSubstitution: 'pull_up',
    },
    {
      id: 'db_row',
      name: 'Dumbbell Row',
      equipment: ['dumbbells'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 2,
      instructions: 'Hinge at hips, one hand on support. Row dumbbell to hip, squeeze shoulder blade.',
      harderSubstitution: 'db_bent_over_row',
    },
    {
      id: 'db_bent_over_row',
      name: 'Dumbbell Bent-Over Row',
      equipment: ['dumbbells'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 3,
      instructions: 'Hinge forward 45°, row both dumbbells simultaneously to hips.',
      easierSubstitution: 'db_row',
    },
    {
      id: 'band_row',
      name: 'Band Row',
      equipment: ['resistance_bands'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 1,
      instructions: 'Anchor band at waist height. Pull handles to sides, squeezing shoulder blades.',
      harderSubstitution: 'band_face_pull',
    },
    {
      id: 'band_face_pull',
      name: 'Band Face Pull',
      equipment: ['resistance_bands'],
      primaryMuscle: 'back',
      secondaryMuscles: ['shoulders'],
      movementPattern: 'pull',
      difficultyTier: 2,
      instructions: 'Anchor band at face height. Pull to face, rotating hands outward. Squeeze rear delts.',
      easierSubstitution: 'band_row',
    },
    {
      id: 'band_pull_apart',
      name: 'Band Pull-Apart',
      equipment: ['resistance_bands'],
      primaryMuscle: 'back',
      secondaryMuscles: ['shoulders'],
      movementPattern: 'pull',
      difficultyTier: 1,
      instructions: 'Hold band at shoulder width, arms extended. Pull apart until band touches chest.',
    },

    // ── SHOULDERS ──
    {
      id: 'pike_push_up',
      name: 'Pike Push-Up',
      equipment: ['bodyweight'],
      primaryMuscle: 'shoulders',
      secondaryMuscles: ['triceps'],
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Hips high in an inverted V. Bend elbows to lower head toward floor, then press up.',
      easierSubstitution: 'push_up',
      harderSubstitution: 'decline_pike_push_up',
    },
    {
      id: 'decline_pike_push_up',
      name: 'Decline Pike Push-Up',
      equipment: ['bodyweight'],
      primaryMuscle: 'shoulders',
      secondaryMuscles: ['triceps'],
      movementPattern: 'push',
      difficultyTier: 3,
      instructions: 'Feet elevated on chair. Pike position. Lower head toward floor and press up.',
      easierSubstitution: 'pike_push_up',
    },
    {
      id: 'db_shoulder_press',
      name: 'Dumbbell Shoulder Press',
      equipment: ['dumbbells'],
      primaryMuscle: 'shoulders',
      secondaryMuscles: ['triceps'],
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Seated or standing, press dumbbells overhead from shoulder height.',
      harderSubstitution: 'db_arnold_press',
    },
    {
      id: 'db_arnold_press',
      name: 'Arnold Press',
      equipment: ['dumbbells'],
      primaryMuscle: 'shoulders',
      secondaryMuscles: ['triceps'],
      movementPattern: 'push',
      difficultyTier: 3,
      instructions: 'Start with palms facing you. Rotate palms outward as you press overhead.',
      easierSubstitution: 'db_shoulder_press',
    },
    {
      id: 'db_lateral_raise',
      name: 'Dumbbell Lateral Raise',
      equipment: ['dumbbells'],
      primaryMuscle: 'shoulders',
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Arms at sides, raise dumbbells out to shoulder height. Slight bend in elbows.',
    },
    {
      id: 'band_shoulder_press',
      name: 'Band Shoulder Press',
      equipment: ['resistance_bands'],
      primaryMuscle: 'shoulders',
      secondaryMuscles: ['triceps'],
      movementPattern: 'push',
      difficultyTier: 1,
      instructions: 'Stand on band, press handles overhead. Control the return.',
    },

    // ── ARMS ──
    {
      id: 'db_bicep_curl',
      name: 'Dumbbell Bicep Curl',
      equipment: ['dumbbells'],
      primaryMuscle: 'biceps',
      movementPattern: 'pull',
      difficultyTier: 1,
      instructions: 'Stand with dumbbells at sides. Curl to shoulders, lower with control.',
      harderSubstitution: 'db_hammer_curl',
    },
    {
      id: 'db_hammer_curl',
      name: 'Dumbbell Hammer Curl',
      equipment: ['dumbbells'],
      primaryMuscle: 'biceps',
      movementPattern: 'pull',
      difficultyTier: 2,
      instructions: 'Palms facing each other. Curl dumbbells to shoulders.',
      easierSubstitution: 'db_bicep_curl',
    },
    {
      id: 'band_bicep_curl',
      name: 'Band Bicep Curl',
      equipment: ['resistance_bands'],
      primaryMuscle: 'biceps',
      movementPattern: 'pull',
      difficultyTier: 1,
      instructions: 'Stand on band, curl handles to shoulders. Keep elbows at sides.',
    },
    {
      id: 'tricep_dip',
      name: 'Tricep Dip (Chair)',
      equipment: ['bodyweight'],
      primaryMuscle: 'triceps',
      secondaryMuscles: ['chest', 'shoulders'],
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Hands on chair edge behind you, lower body by bending elbows to 90°, press up.',
      easierSubstitution: 'push_up',
    },
    {
      id: 'db_tricep_extension',
      name: 'Dumbbell Tricep Extension',
      equipment: ['dumbbells'],
      primaryMuscle: 'triceps',
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Hold one dumbbell overhead with both hands. Lower behind head, extend up.',
    },
    {
      id: 'band_tricep_pushdown',
      name: 'Band Tricep Pushdown',
      equipment: ['resistance_bands'],
      primaryMuscle: 'triceps',
      movementPattern: 'push',
      difficultyTier: 1,
      instructions: 'Anchor band above. Push handles down, extending elbows fully. Keep elbows at sides.',
    },

    // ── LEGS ──
    {
      id: 'bodyweight_squat',
      name: 'Bodyweight Squat',
      equipment: ['bodyweight'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes'],
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'Feet shoulder-width. Sit back and down, thighs parallel. Drive up through heels.',
      harderSubstitution: 'jump_squat',
    },
    {
      id: 'jump_squat',
      name: 'Jump Squat',
      equipment: ['bodyweight'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes', 'calves'],
      movementPattern: 'legs',
      difficultyTier: 3,
      instructions: 'Squat down, then explode upward. Land softly and immediately descend again.',
      easierSubstitution: 'bodyweight_squat',
    },
    {
      id: 'goblet_squat',
      name: 'Goblet Squat',
      equipment: ['dumbbells'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes', 'core'],
      movementPattern: 'legs',
      difficultyTier: 2,
      instructions: 'Hold dumbbell at chest. Squat deep, elbows between knees. Drive up.',
      easierSubstitution: 'bodyweight_squat',
    },
    {
      id: 'band_squat',
      name: 'Band Squat',
      equipment: ['resistance_bands'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes'],
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'Stand on band, hold handles at shoulders. Squat and stand.',
    },
    {
      id: 'forward_lunge',
      name: 'Forward Lunge',
      equipment: ['bodyweight'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes', 'hamstrings'],
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'Step forward, lower back knee toward floor. Push back to start. Alternate legs.',
      harderSubstitution: 'bulgarian_split_squat',
    },
    {
      id: 'bulgarian_split_squat',
      name: 'Bulgarian Split Squat',
      equipment: ['bodyweight'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes'],
      movementPattern: 'legs',
      difficultyTier: 3,
      instructions: 'Rear foot elevated on bench/chair. Lower until front thigh is parallel. Drive up.',
      easierSubstitution: 'forward_lunge',
    },
    {
      id: 'db_lunge',
      name: 'Dumbbell Lunge',
      equipment: ['dumbbells'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes', 'hamstrings'],
      movementPattern: 'legs',
      difficultyTier: 2,
      instructions: 'Hold dumbbells at sides. Step forward into lunge, alternate legs.',
      easierSubstitution: 'forward_lunge',
    },
    {
      id: 'glute_bridge',
      name: 'Glute Bridge',
      equipment: ['bodyweight'],
      primaryMuscle: 'glutes',
      secondaryMuscles: ['hamstrings'],
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'Lie on back, feet flat. Drive hips up, squeeze glutes at top. Lower with control.',
      harderSubstitution: 'single_leg_glute_bridge',
    },
    {
      id: 'single_leg_glute_bridge',
      name: 'Single-Leg Glute Bridge',
      equipment: ['bodyweight'],
      primaryMuscle: 'glutes',
      secondaryMuscles: ['hamstrings'],
      movementPattern: 'legs',
      difficultyTier: 3,
      instructions: 'One leg extended. Drive hips up on the planted foot. Squeeze at top.',
      easierSubstitution: 'glute_bridge',
    },
    {
      id: 'db_rdl',
      name: 'Dumbbell Romanian Deadlift',
      equipment: ['dumbbells'],
      primaryMuscle: 'hamstrings',
      secondaryMuscles: ['glutes', 'back'],
      movementPattern: 'legs',
      difficultyTier: 2,
      instructions: 'Hold dumbbells, hinge at hips pushing hips back. Slight knee bend. Feel hamstring stretch.',
    },
    {
      id: 'nordic_curl_negative',
      name: 'Nordic Curl (Negative)',
      equipment: ['bodyweight'],
      primaryMuscle: 'hamstrings',
      movementPattern: 'legs',
      difficultyTier: 4,
      instructions: 'Kneel with feet anchored. Slowly lower body forward using hamstrings. Push back up from floor.',
      easierSubstitution: 'glute_bridge',
    },
    {
      id: 'calf_raise',
      name: 'Calf Raise',
      equipment: ['bodyweight'],
      primaryMuscle: 'calves',
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'Stand on edge of step. Rise up on toes, lower heels below step level.',
    },
    {
      id: 'db_calf_raise',
      name: 'Dumbbell Calf Raise',
      equipment: ['dumbbells'],
      primaryMuscle: 'calves',
      movementPattern: 'legs',
      difficultyTier: 2,
      instructions: 'Hold dumbbells at sides. Rise up on toes, pause, lower slowly.',
      easierSubstitution: 'calf_raise',
    },

    // ── CORE ──
    {
      id: 'plank',
      name: 'Plank',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 1,
      instructions: 'Forearms on floor, body straight from head to heels. Hold position. Breathe steadily.',
      harderSubstitution: 'plank_shoulder_tap',
    },
    {
      id: 'plank_shoulder_tap',
      name: 'Plank Shoulder Tap',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 2,
      instructions: 'High plank. Tap opposite shoulder with each hand, minimizing hip rotation.',
      easierSubstitution: 'plank',
    },
    {
      id: 'dead_bug',
      name: 'Dead Bug',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 1,
      instructions: 'Lie on back, arms up, knees at 90°. Extend opposite arm and leg. Keep lower back pressed down.',
    },
    {
      id: 'mountain_climber',
      name: 'Mountain Climber',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      secondaryMuscles: ['shoulders'],
      movementPattern: 'core',
      difficultyTier: 2,
      instructions: 'High plank. Drive knees to chest alternately at a brisk pace.',
    },
    {
      id: 'bicycle_crunch',
      name: 'Bicycle Crunch',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 2,
      instructions: 'Lie on back, hands behind head. Rotate elbow to opposite knee, alternating sides.',
    },
    {
      id: 'russian_twist',
      name: 'Russian Twist',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 2,
      instructions: 'Seated, lean back slightly, feet off floor. Rotate torso side to side.',
      harderSubstitution: 'db_russian_twist',
    },
    {
      id: 'db_russian_twist',
      name: 'Dumbbell Russian Twist',
      equipment: ['dumbbells'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 3,
      instructions: 'Same as Russian Twist but holding a dumbbell for added resistance.',
      easierSubstitution: 'russian_twist',
    },
    {
      id: 'leg_raise',
      name: 'Leg Raise',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 2,
      instructions: 'Lie on back, legs straight. Raise legs to 90° then lower slowly. Keep lower back flat.',
    },

    // ── BODYWEIGHT (additional) ──
    {
      id: 'chin_up',
      name: 'Chin-Up',
      equipment: ['pull_up_bar'],
      primaryMuscle: 'biceps',
      secondaryMuscles: ['back'],
      movementPattern: 'pull',
      difficultyTier: 3,
      instructions: 'Hang from bar with palms facing you. Pull chin above bar. Lower with control.',
      easierSubstitution: 'inverted_row',
      harderSubstitution: 'pull_up',
    },
    {
      id: 'wide_push_up',
      name: 'Wide Push-Up',
      equipment: ['bodyweight'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['shoulders', 'triceps'],
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Hands wider than shoulder-width. Lower chest to floor and press up. Emphasizes outer chest.',
      easierSubstitution: 'push_up',
      harderSubstitution: 'archer_push_up',
    },
    {
      id: 'incline_push_up',
      name: 'Incline Push-Up',
      equipment: ['bodyweight'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['triceps', 'shoulders'],
      movementPattern: 'push',
      difficultyTier: 1,
      instructions: 'Hands on elevated surface (bench, step). Lower chest to surface and press up. Great for beginners.',
      harderSubstitution: 'push_up',
    },
    {
      id: 'decline_push_up',
      name: 'Decline Push-Up',
      equipment: ['bodyweight'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['shoulders', 'triceps'],
      movementPattern: 'push',
      difficultyTier: 3,
      instructions: 'Feet elevated on bench or step. Lower chest to floor and press up. Targets upper chest.',
      easierSubstitution: 'push_up',
      harderSubstitution: 'archer_push_up',
    },
    {
      id: 'dip',
      name: 'Dip (Parallel Bars)',
      equipment: ['bodyweight'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['triceps', 'shoulders'],
      movementPattern: 'push',
      difficultyTier: 3,
      instructions: 'Support yourself on parallel bars. Lower body by bending elbows, lean slightly forward. Press up.',
      easierSubstitution: 'tricep_dip',
    },
    {
      id: 'pistol_squat',
      name: 'Pistol Squat',
      equipment: ['bodyweight'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes', 'core'],
      movementPattern: 'legs',
      difficultyTier: 5,
      instructions: 'Stand on one leg, extend the other forward. Squat all the way down and stand back up.',
      easierSubstitution: 'bulgarian_split_squat',
    },
    {
      id: 'wall_sit',
      name: 'Wall Sit',
      equipment: ['bodyweight'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes'],
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'Back against wall, slide down until thighs are parallel to floor. Hold the position.',
    },
    {
      id: 'step_up',
      name: 'Step-Up',
      equipment: ['bodyweight'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes'],
      movementPattern: 'legs',
      difficultyTier: 2,
      instructions: 'Step onto a bench or sturdy platform with one foot. Drive up, then step down. Alternate legs.',
      easierSubstitution: 'forward_lunge',
      harderSubstitution: 'bulgarian_split_squat',
    },
    {
      id: 'reverse_lunge',
      name: 'Reverse Lunge',
      equipment: ['bodyweight'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes', 'hamstrings'],
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'Step backward into a lunge, lower back knee toward floor. Push off back foot to return. Alternate legs.',
      harderSubstitution: 'bulgarian_split_squat',
    },
    {
      id: 'side_lunge',
      name: 'Side Lunge',
      equipment: ['bodyweight'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes', 'hamstrings'],
      movementPattern: 'legs',
      difficultyTier: 2,
      instructions: 'Step wide to one side, bend that knee and sit back. Keep other leg straight. Push back to start.',
    },
    {
      id: 'donkey_kick',
      name: 'Donkey Kick',
      equipment: ['bodyweight'],
      primaryMuscle: 'glutes',
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'On all fours, drive one foot toward the ceiling keeping knee bent at 90 degrees. Squeeze glute at top.',
    },
    {
      id: 'fire_hydrant',
      name: 'Fire Hydrant',
      equipment: ['bodyweight'],
      primaryMuscle: 'glutes',
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'On all fours, lift one knee out to the side keeping it bent. Squeeze at top. Return slowly.',
    },
    {
      id: 'hip_thrust',
      name: 'Hip Thrust (Bodyweight)',
      equipment: ['bodyweight'],
      primaryMuscle: 'glutes',
      secondaryMuscles: ['hamstrings'],
      movementPattern: 'legs',
      difficultyTier: 2,
      instructions: 'Upper back on bench, feet flat on floor. Drive hips up until thighs are parallel to floor. Squeeze glutes.',
      easierSubstitution: 'glute_bridge',
    },
    {
      id: 'superman',
      name: 'Superman',
      equipment: ['bodyweight'],
      primaryMuscle: 'back',
      secondaryMuscles: ['glutes'],
      movementPattern: 'pull',
      difficultyTier: 1,
      instructions: 'Lie face down. Simultaneously lift arms, chest, and legs off the floor. Hold briefly, then lower.',
    },
    {
      id: 'burpee',
      name: 'Burpee',
      equipment: ['bodyweight'],
      primaryMuscle: 'full_body',
      secondaryMuscles: ['chest', 'quads', 'core'],
      movementPattern: 'compound',
      difficultyTier: 3,
      instructions: 'Squat down, kick feet back to plank, do a push-up, jump feet forward, jump up with arms overhead.',
    },
    {
      id: 'bear_crawl',
      name: 'Bear Crawl',
      equipment: ['bodyweight'],
      primaryMuscle: 'full_body',
      secondaryMuscles: ['shoulders', 'core', 'quads'],
      movementPattern: 'compound',
      difficultyTier: 2,
      instructions: 'On all fours with knees hovering off ground. Crawl forward moving opposite hand and foot together.',
    },
    {
      id: 'hanging_leg_raise',
      name: 'Hanging Leg Raise',
      equipment: ['pull_up_bar'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 3,
      instructions: 'Hang from bar. Raise legs to 90 degrees keeping them straight. Lower with control.',
      easierSubstitution: 'leg_raise',
    },
    {
      id: 'v_up',
      name: 'V-Up',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 3,
      instructions: 'Lie flat. Simultaneously raise legs and torso to touch toes at the top, forming a V shape.',
      easierSubstitution: 'bicycle_crunch',
    },
    {
      id: 'side_plank',
      name: 'Side Plank',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 2,
      instructions: 'Lie on your side, prop up on forearm. Lift hips so body forms a straight line. Hold.',
      easierSubstitution: 'plank',
    },
    {
      id: 'flutter_kick',
      name: 'Flutter Kick',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 2,
      instructions: 'Lie on back, legs slightly off ground. Alternate small up-and-down kicks. Keep lower back flat.',
    },

    // ── BARBELL ──
    {
      id: 'bb_bench_press',
      name: 'Barbell Bench Press',
      equipment: ['barbell', 'bench'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['triceps', 'shoulders'],
      movementPattern: 'push',
      difficultyTier: 3,
      instructions: 'Lie on bench, grip bar slightly wider than shoulders. Lower to chest, press up. Keep feet flat.',
      easierSubstitution: 'db_bench_press',
    },
    {
      id: 'bb_incline_bench',
      name: 'Barbell Incline Bench Press',
      equipment: ['barbell', 'bench'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['shoulders', 'triceps'],
      movementPattern: 'push',
      difficultyTier: 3,
      instructions: 'Bench at 30-45 degrees. Lower bar to upper chest, press up.',
      easierSubstitution: 'db_incline_press',
    },
    {
      id: 'bb_overhead_press',
      name: 'Barbell Overhead Press',
      equipment: ['barbell'],
      primaryMuscle: 'shoulders',
      secondaryMuscles: ['triceps', 'core'],
      movementPattern: 'push',
      difficultyTier: 3,
      instructions: 'Stand with bar at shoulders. Press overhead until arms are locked out. Lower with control.',
      easierSubstitution: 'db_shoulder_press',
    },
    {
      id: 'bb_back_squat',
      name: 'Barbell Back Squat',
      equipment: ['barbell'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes', 'hamstrings', 'core'],
      movementPattern: 'legs',
      difficultyTier: 3,
      instructions: 'Bar on upper back. Squat until thighs are parallel or below. Drive up through heels.',
      easierSubstitution: 'goblet_squat',
    },
    {
      id: 'bb_front_squat',
      name: 'Barbell Front Squat',
      equipment: ['barbell'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes', 'core'],
      movementPattern: 'legs',
      difficultyTier: 4,
      instructions: 'Bar racked on front delts. Squat deep keeping elbows high and torso upright. Drive up.',
      easierSubstitution: 'bb_back_squat',
    },
    {
      id: 'bb_deadlift',
      name: 'Barbell Deadlift',
      equipment: ['barbell'],
      primaryMuscle: 'hamstrings',
      secondaryMuscles: ['glutes', 'back', 'core'],
      movementPattern: 'legs',
      difficultyTier: 3,
      instructions: 'Feet hip-width, grip bar outside knees. Drive through floor, extending hips and knees together. Keep back flat.',
    },
    {
      id: 'bb_rdl',
      name: 'Barbell Romanian Deadlift',
      equipment: ['barbell'],
      primaryMuscle: 'hamstrings',
      secondaryMuscles: ['glutes', 'back'],
      movementPattern: 'legs',
      difficultyTier: 3,
      instructions: 'Hold bar at hips. Hinge forward pushing hips back, slight knee bend. Feel hamstring stretch, then drive hips forward.',
      easierSubstitution: 'db_rdl',
    },
    {
      id: 'bb_bent_over_row',
      name: 'Barbell Bent-Over Row',
      equipment: ['barbell'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 3,
      instructions: 'Hinge at hips, grip bar shoulder-width. Row bar to lower chest. Squeeze shoulder blades.',
      easierSubstitution: 'db_bent_over_row',
    },
    {
      id: 'bb_curl',
      name: 'Barbell Curl',
      equipment: ['barbell'],
      primaryMuscle: 'biceps',
      movementPattern: 'pull',
      difficultyTier: 2,
      instructions: 'Stand with bar at thighs, palms up. Curl to shoulders keeping elbows pinned at sides.',
      easierSubstitution: 'db_bicep_curl',
    },
    {
      id: 'bb_skull_crusher',
      name: 'Barbell Skull Crusher',
      equipment: ['barbell', 'bench'],
      primaryMuscle: 'triceps',
      movementPattern: 'push',
      difficultyTier: 3,
      instructions: 'Lie on bench, arms extended holding bar. Lower bar toward forehead by bending elbows. Extend back up.',
      easierSubstitution: 'db_tricep_extension',
    },
    {
      id: 'bb_hip_thrust',
      name: 'Barbell Hip Thrust',
      equipment: ['barbell', 'bench'],
      primaryMuscle: 'glutes',
      secondaryMuscles: ['hamstrings'],
      movementPattern: 'legs',
      difficultyTier: 3,
      instructions: 'Upper back on bench, bar across hips. Drive hips up squeezing glutes at top. Lower with control.',
      easierSubstitution: 'hip_thrust',
    },

    // ── KETTLEBELL ──
    {
      id: 'kb_swing',
      name: 'Kettlebell Swing',
      equipment: ['kettlebell'],
      primaryMuscle: 'glutes',
      secondaryMuscles: ['hamstrings', 'core', 'shoulders'],
      movementPattern: 'compound',
      difficultyTier: 2,
      instructions: 'Hinge at hips, swing kettlebell between legs. Drive hips forward explosively to swing it to chest height.',
    },
    {
      id: 'kb_goblet_squat',
      name: 'Kettlebell Goblet Squat',
      equipment: ['kettlebell'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes', 'core'],
      movementPattern: 'legs',
      difficultyTier: 2,
      instructions: 'Hold kettlebell at chest by the horns. Squat deep with elbows between knees. Stand up.',
    },
    {
      id: 'kb_turkish_getup',
      name: 'Turkish Get-Up',
      equipment: ['kettlebell'],
      primaryMuscle: 'full_body',
      secondaryMuscles: ['shoulders', 'core', 'glutes'],
      movementPattern: 'compound',
      difficultyTier: 4,
      instructions: 'Lie down holding kettlebell overhead. Stand up in a sequence of movements while keeping the bell locked out above you.',
    },
    {
      id: 'kb_clean_and_press',
      name: 'Kettlebell Clean & Press',
      equipment: ['kettlebell'],
      primaryMuscle: 'shoulders',
      secondaryMuscles: ['core', 'back'],
      movementPattern: 'compound',
      difficultyTier: 3,
      instructions: 'Swing kettlebell to rack position at shoulder. Press overhead. Lower back to rack, then swing down. Repeat.',
    },

    // ── CABLE MACHINE ──
    {
      id: 'cable_chest_fly',
      name: 'Cable Chest Fly',
      equipment: ['cable_machine'],
      primaryMuscle: 'chest',
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Set pulleys at chest height. Step forward, bring handles together in front of chest with slight elbow bend.',
    },
    {
      id: 'cable_crossover',
      name: 'Cable Crossover',
      equipment: ['cable_machine'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['shoulders'],
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Set pulleys high. Step forward and bring handles down and together in front of hips. Squeeze chest.',
      easierSubstitution: 'cable_chest_fly',
    },
    {
      id: 'cable_lat_pulldown',
      name: 'Lat Pulldown',
      equipment: ['cable_machine'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 2,
      instructions: 'Sit at lat pulldown machine. Pull bar to upper chest, squeezing shoulder blades together. Return slowly.',
      harderSubstitution: 'pull_up',
    },
    {
      id: 'cable_seated_row',
      name: 'Cable Seated Row',
      equipment: ['cable_machine'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 2,
      instructions: 'Sit upright, feet on platform. Pull handle to lower chest. Squeeze shoulder blades. Return with control.',
    },
    {
      id: 'cable_face_pull',
      name: 'Cable Face Pull',
      equipment: ['cable_machine'],
      primaryMuscle: 'shoulders',
      secondaryMuscles: ['back'],
      movementPattern: 'pull',
      difficultyTier: 2,
      instructions: 'Set pulley at face height with rope. Pull toward face, rotating hands outward. Squeeze rear delts.',
      easierSubstitution: 'band_face_pull',
    },
    {
      id: 'cable_tricep_pushdown',
      name: 'Cable Tricep Pushdown',
      equipment: ['cable_machine'],
      primaryMuscle: 'triceps',
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Set pulley high with bar or rope. Push down extending elbows fully. Keep elbows at sides.',
    },
    {
      id: 'cable_bicep_curl',
      name: 'Cable Bicep Curl',
      equipment: ['cable_machine'],
      primaryMuscle: 'biceps',
      movementPattern: 'pull',
      difficultyTier: 2,
      instructions: 'Set pulley low with bar. Curl handles to shoulders. Keep elbows pinned. Lower with control.',
    },
    {
      id: 'cable_lateral_raise',
      name: 'Cable Lateral Raise',
      equipment: ['cable_machine'],
      primaryMuscle: 'shoulders',
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Set pulley low. Stand sideways, raise handle out to shoulder height with slight elbow bend. Lower slowly.',
    },
    {
      id: 'cable_woodchop',
      name: 'Cable Woodchop',
      equipment: ['cable_machine'],
      primaryMuscle: 'core',
      secondaryMuscles: ['shoulders'],
      movementPattern: 'core',
      difficultyTier: 2,
      instructions: 'Set pulley high. Stand sideways, pull handle diagonally across body from high to low. Rotate torso.',
    },

    // ── GYM MACHINES ──
    {
      id: 'machine_chest_press',
      name: 'Machine Chest Press',
      equipment: ['machine'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['triceps', 'shoulders'],
      movementPattern: 'push',
      difficultyTier: 1,
      instructions: 'Sit with back flat against pad. Press handles forward until arms are extended. Return slowly.',
      harderSubstitution: 'db_bench_press',
    },
    {
      id: 'machine_shoulder_press',
      name: 'Machine Shoulder Press',
      equipment: ['machine'],
      primaryMuscle: 'shoulders',
      secondaryMuscles: ['triceps'],
      movementPattern: 'push',
      difficultyTier: 1,
      instructions: 'Sit with back supported. Press handles overhead. Lower to ear level with control.',
      harderSubstitution: 'db_shoulder_press',
    },
    {
      id: 'machine_pec_deck',
      name: 'Pec Deck (Machine Fly)',
      equipment: ['machine'],
      primaryMuscle: 'chest',
      movementPattern: 'push',
      difficultyTier: 1,
      instructions: 'Sit with arms on pads at chest height. Bring pads together in front. Squeeze chest, return slowly.',
    },
    {
      id: 'machine_lat_pulldown',
      name: 'Machine Lat Pulldown',
      equipment: ['machine'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 1,
      instructions: 'Sit at machine, grip handles above. Pull down to upper chest. Return with control.',
      harderSubstitution: 'cable_lat_pulldown',
    },
    {
      id: 'machine_seated_row',
      name: 'Machine Seated Row',
      equipment: ['machine'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 1,
      instructions: 'Sit with chest against pad. Pull handles toward you, squeezing shoulder blades. Return slowly.',
    },
    {
      id: 'machine_rear_delt_fly',
      name: 'Machine Rear Delt Fly',
      equipment: ['machine'],
      primaryMuscle: 'shoulders',
      secondaryMuscles: ['back'],
      movementPattern: 'pull',
      difficultyTier: 1,
      instructions: 'Sit facing the pec deck pad. Grip handles and pull arms back, squeezing rear delts.',
    },
    {
      id: 'machine_leg_press',
      name: 'Leg Press',
      equipment: ['machine'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes', 'hamstrings'],
      movementPattern: 'legs',
      difficultyTier: 2,
      instructions: 'Sit in machine, feet shoulder-width on platform. Press platform away, then lower with control. Do not lock knees.',
      easierSubstitution: 'bodyweight_squat',
    },
    {
      id: 'machine_leg_extension',
      name: 'Leg Extension',
      equipment: ['machine'],
      primaryMuscle: 'quads',
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'Sit in machine, pad on shins. Extend legs until straight. Squeeze quads at top. Lower slowly.',
    },
    {
      id: 'machine_leg_curl',
      name: 'Leg Curl',
      equipment: ['machine'],
      primaryMuscle: 'hamstrings',
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'Lie face down or sit in machine. Curl pad toward glutes. Squeeze hamstrings. Return slowly.',
    },
    {
      id: 'machine_hack_squat',
      name: 'Hack Squat',
      equipment: ['machine'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes'],
      movementPattern: 'legs',
      difficultyTier: 2,
      instructions: 'Back against pad, feet on platform. Squat down until thighs are parallel. Drive up through heels.',
    },
    {
      id: 'machine_hip_abduction',
      name: 'Hip Abduction Machine',
      equipment: ['machine'],
      primaryMuscle: 'glutes',
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'Sit in machine, pads on outer thighs. Push legs apart against resistance. Return slowly.',
    },
    {
      id: 'machine_hip_adduction',
      name: 'Hip Adduction Machine',
      equipment: ['machine'],
      primaryMuscle: 'quads',
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'Sit in machine, pads on inner thighs. Squeeze legs together against resistance. Return slowly.',
    },
    {
      id: 'machine_calf_raise',
      name: 'Machine Calf Raise',
      equipment: ['machine'],
      primaryMuscle: 'calves',
      movementPattern: 'legs',
      difficultyTier: 2,
      instructions: 'Sit or stand in calf raise machine. Rise up on toes, pause at top. Lower heels below platform.',
      easierSubstitution: 'calf_raise',
    },
    {
      id: 'smith_machine_squat',
      name: 'Smith Machine Squat',
      equipment: ['machine'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes', 'hamstrings'],
      movementPattern: 'legs',
      difficultyTier: 2,
      instructions: 'Bar on upper back in Smith machine. Squat until thighs parallel. The guided bar path adds stability.',
      easierSubstitution: 'bodyweight_squat',
      harderSubstitution: 'bb_back_squat',
    },
    {
      id: 'assisted_pull_up',
      name: 'Assisted Pull-Up Machine',
      equipment: ['machine'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 1,
      instructions: 'Kneel on pad, grip bar. Pull chin above bar with machine assistance. Lower slowly. Reduce assistance over time.',
      harderSubstitution: 'pull_up',
    },
    {
      id: 'assisted_dip',
      name: 'Assisted Dip Machine',
      equipment: ['machine'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['triceps', 'shoulders'],
      movementPattern: 'push',
      difficultyTier: 1,
      instructions: 'Kneel on pad, grip handles. Lower body by bending elbows, lean forward slightly. Press up. Reduce assistance over time.',
      harderSubstitution: 'dip',
    },
    // ── TRX / SUSPENSION ──
    {
      id: 'trx_row',
      name: 'TRX Row',
      equipment: ['trx'],
      primaryMuscle: 'back',
      secondaryMuscles: ['biceps', 'core'],
      movementPattern: 'pull',
      difficultyTier: 2,
      instructions: 'Lean back holding TRX handles, body straight. Pull chest to handles squeezing shoulder blades. Lower with control.',
      easierSubstitution: 'inverted_row',
      harderSubstitution: 'pull_up',
    },
    {
      id: 'trx_chest_press',
      name: 'TRX Chest Press',
      equipment: ['trx'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['triceps', 'shoulders', 'core'],
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Face away from anchor, arms extended holding handles. Lower chest between hands, then press back up. Keep core tight.',
      easierSubstitution: 'push_up',
    },
    {
      id: 'trx_fly',
      name: 'TRX Fly',
      equipment: ['trx'],
      primaryMuscle: 'chest',
      secondaryMuscles: ['shoulders', 'core'],
      movementPattern: 'push',
      difficultyTier: 3,
      instructions: 'Face away from anchor. Open arms wide with slight elbow bend, then bring handles together in front of chest.',
      easierSubstitution: 'trx_chest_press',
    },
    {
      id: 'trx_bicep_curl',
      name: 'TRX Bicep Curl',
      equipment: ['trx'],
      primaryMuscle: 'biceps',
      movementPattern: 'pull',
      difficultyTier: 2,
      instructions: 'Face anchor, lean back with arms extended. Curl handles toward forehead keeping elbows high. Extend back out.',
    },
    {
      id: 'trx_tricep_extension',
      name: 'TRX Tricep Extension',
      equipment: ['trx'],
      primaryMuscle: 'triceps',
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Face away from anchor, arms overhead holding handles. Lower body by bending elbows, then extend to press back up.',
    },
    {
      id: 'trx_y_fly',
      name: 'TRX Y-Fly',
      equipment: ['trx'],
      primaryMuscle: 'shoulders',
      secondaryMuscles: ['back'],
      movementPattern: 'pull',
      difficultyTier: 2,
      instructions: 'Face anchor, lean back. Pull body up while raising arms into a Y shape overhead. Squeeze shoulder blades.',
    },
    {
      id: 'trx_squat',
      name: 'TRX Squat',
      equipment: ['trx'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes'],
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'Hold handles at chest, lean back slightly. Squat deep using the straps for balance. Drive up through heels.',
      harderSubstitution: 'trx_pistol_squat',
    },
    {
      id: 'trx_pistol_squat',
      name: 'TRX Pistol Squat',
      equipment: ['trx'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes', 'core'],
      movementPattern: 'legs',
      difficultyTier: 4,
      instructions: 'Hold handles for balance. Extend one leg forward and squat all the way down on the other. Stand back up.',
      easierSubstitution: 'trx_squat',
    },
    {
      id: 'trx_lunge',
      name: 'TRX Suspended Lunge',
      equipment: ['trx'],
      primaryMuscle: 'quads',
      secondaryMuscles: ['glutes', 'hamstrings'],
      movementPattern: 'legs',
      difficultyTier: 3,
      instructions: 'One foot in strap behind you. Lunge down on front leg until thigh is parallel. Drive back up.',
      easierSubstitution: 'forward_lunge',
    },
    {
      id: 'trx_hamstring_curl',
      name: 'TRX Hamstring Curl',
      equipment: ['trx'],
      primaryMuscle: 'hamstrings',
      secondaryMuscles: ['glutes', 'core'],
      movementPattern: 'legs',
      difficultyTier: 3,
      instructions: 'Lie on back, heels in straps. Lift hips, then curl heels toward glutes. Extend back out. Keep hips elevated.',
      easierSubstitution: 'glute_bridge',
    },
    {
      id: 'trx_plank',
      name: 'TRX Plank',
      equipment: ['trx'],
      primaryMuscle: 'core',
      secondaryMuscles: ['shoulders'],
      movementPattern: 'core',
      difficultyTier: 2,
      instructions: 'Feet in straps, forearms on floor. Hold plank position. The instability forces extra core engagement.',
      easierSubstitution: 'plank',
      harderSubstitution: 'trx_pike',
    },
    {
      id: 'trx_pike',
      name: 'TRX Pike',
      equipment: ['trx'],
      primaryMuscle: 'core',
      secondaryMuscles: ['shoulders'],
      movementPattern: 'core',
      difficultyTier: 4,
      instructions: 'Feet in straps, hands on floor in push-up position. Pike hips up toward ceiling keeping legs straight. Lower back to plank.',
      easierSubstitution: 'trx_plank',
    },
    {
      id: 'trx_mountain_climber',
      name: 'TRX Mountain Climber',
      equipment: ['trx'],
      primaryMuscle: 'core',
      secondaryMuscles: ['shoulders', 'quads'],
      movementPattern: 'core',
      difficultyTier: 3,
      instructions: 'Feet in straps, push-up position. Drive knees to chest alternately. The suspension adds instability.',
      easierSubstitution: 'mountain_climber',
    },

    // ── PILATES (Core / Bodyweight) ──
    {
      id: 'the_hundred',
      name: 'The Hundred',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 2,
      instructions: 'Lie on back, lift legs to tabletop or extended. Lift head and shoulders, pump arms up and down vigorously. Inhale 5 counts, exhale 5 counts. Builds endurance and warms up the body.',
    },
    {
      id: 'roll_up',
      name: 'Roll Up',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 2,
      instructions: 'Lie flat, arms overhead. Slowly peel spine off the mat one vertebra at a time to a seated position, then roll back down with control. Improves spinal articulation and core control.',
    },
    {
      id: 'single_leg_stretch',
      name: 'Single Leg Stretch',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 2,
      instructions: 'Lie on back, shoulders lifted. Pull one knee to chest while extending the other leg. Alternate sides with control. Strengthens lower abs and coordination.',
    },
    {
      id: 'double_leg_stretch',
      name: 'Double Leg Stretch',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 3,
      instructions: 'Lie on back, shoulders lifted, knees to chest. Extend arms and legs out simultaneously, then circle arms back and draw knees in. Deep abdominal control.',
      easierSubstitution: 'single_leg_stretch',
    },
    {
      id: 'criss_cross',
      name: 'Criss Cross',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 2,
      instructions: 'Lie on back, hands behind head. Lift shoulders and twist elbow toward opposite knee in a bicycle motion, targeting obliques. Keep lower back pressed into the mat.',
    },
    {
      id: 'shoulder_bridge',
      name: 'Shoulder Bridge',
      equipment: ['bodyweight'],
      primaryMuscle: 'glutes',
      secondaryMuscles: ['hamstrings', 'core'],
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'Lie on back, feet planted hip-width. Lift hips to form a straight line from shoulders to knees. Hold and lower with control. Builds glute strength and spinal stability.',
      harderSubstitution: 'single_leg_glute_bridge',
    },
    {
      id: 'side_kick_series',
      name: 'Side Kick Series',
      equipment: ['bodyweight'],
      primaryMuscle: 'glutes',
      secondaryMuscles: ['core', 'quads'],
      movementPattern: 'legs',
      difficultyTier: 2,
      instructions: 'Lie on your side, legs stacked. Perform controlled kicks forward and back, up and down, and small circles. Strengthens hips and improves balance.',
    },
    {
      id: 'single_leg_kick',
      name: 'Single Leg Kick',
      equipment: ['bodyweight'],
      primaryMuscle: 'hamstrings',
      secondaryMuscles: ['glutes', 'core'],
      movementPattern: 'legs',
      difficultyTier: 1,
      instructions: 'Lie face down propped on forearms. Kick one heel toward glutes with a double pulse, then switch. Targets hamstrings and hip mobility.',
    },
    {
      id: 'leg_circles',
      name: 'Leg Circles',
      equipment: ['bodyweight'],
      primaryMuscle: 'core',
      secondaryMuscles: ['quads', 'glutes'],
      movementPattern: 'core',
      difficultyTier: 2,
      instructions: 'Lie on back, one leg lifted to ceiling. Draw controlled circles with the leg, keeping hips stable. Improves hip mobility and lower ab control.',
    },
    {
      id: 'swimming',
      name: 'Swimming',
      equipment: ['bodyweight'],
      primaryMuscle: 'back',
      secondaryMuscles: ['glutes', 'core'],
      movementPattern: 'pull',
      difficultyTier: 2,
      instructions: 'Lie face down, arms extended overhead. Lift chest and alternately raise opposite arm and leg in a flutter pattern. Targets glutes and posterior chain.',
      easierSubstitution: 'superman',
    },

    // ── BICEPS (Dumbbell) ──
    {
      id: 'db_alternating_curl',
      name: 'Alternating Dumbbell Curl',
      equipment: ['dumbbells'],
      primaryMuscle: 'biceps',
      movementPattern: 'pull',
      difficultyTier: 2,
      instructions: 'Stand with dumbbells at sides. Curl one arm up with supinated grip, lower, then curl the other. Allows focus on each arm independently.',
      easierSubstitution: 'db_bicep_curl',
    },
    {
      id: 'db_concentration_curl',
      name: 'Concentration Curl',
      equipment: ['dumbbells'],
      primaryMuscle: 'biceps',
      movementPattern: 'pull',
      difficultyTier: 2,
      instructions: 'Sit with elbow braced against inner thigh. Curl dumbbell up with strict form, squeezing at the top. Isolates the bicep with no momentum.',
      easierSubstitution: 'db_bicep_curl',
    },

    // ── TRICEPS (Dumbbell) ──
    {
      id: 'db_tricep_kickback',
      name: 'Triceps Kickback',
      equipment: ['dumbbells'],
      primaryMuscle: 'triceps',
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Hinge forward, upper arm parallel to floor. Extend forearm back until arm is straight, squeeze triceps, then lower with control.',
    },
    {
      id: 'db_skull_crusher',
      name: 'Skull Crushers',
      equipment: ['dumbbells', 'bench'],
      primaryMuscle: 'triceps',
      secondaryMuscles: ['shoulders'],
      movementPattern: 'push',
      difficultyTier: 3,
      instructions: 'Lie on bench holding dumbbells above chest. Lower weights toward forehead by bending elbows, then extend back up. Keep upper arms stationary.',
      easierSubstitution: 'db_tricep_extension',
    },
    {
      id: 'db_close_grip_press',
      name: 'Close-Grip Dumbbell Press',
      equipment: ['dumbbells', 'bench'],
      primaryMuscle: 'triceps',
      secondaryMuscles: ['chest'],
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Lie on bench with dumbbells pressed together, palms facing each other. Press up and lower with elbows close to body. Emphasizes triceps over chest.',
    },

    // ── SHOULDERS (Dumbbell) ──
    {
      id: 'db_front_raise',
      name: 'Front Raise',
      equipment: ['dumbbells'],
      primaryMuscle: 'shoulders',
      movementPattern: 'push',
      difficultyTier: 2,
      instructions: 'Stand with dumbbells in front of thighs. Raise one or both arms straight ahead to shoulder height, then lower with control. Targets front deltoids.',
    },
    {
      id: 'db_upright_row',
      name: 'Upright Row',
      equipment: ['dumbbells'],
      primaryMuscle: 'shoulders',
      secondaryMuscles: ['biceps'],
      movementPattern: 'pull',
      difficultyTier: 2,
      instructions: 'Hold dumbbells in front of thighs. Pull elbows up and out to shoulder height, keeping weights close to body. Lower with control.',
    },
    {
      id: 'db_reverse_fly',
      name: 'Reverse Fly',
      equipment: ['dumbbells'],
      primaryMuscle: 'shoulders',
      secondaryMuscles: ['back'],
      movementPattern: 'pull',
      difficultyTier: 2,
      instructions: 'Hinge forward at hips, dumbbells hanging below. Raise arms out to the sides squeezing shoulder blades together. Targets rear deltoids.',
    },

    // ── WEIGHTED PILATES (Dumbbell + Core) ──
    {
      id: 'weighted_roll_up',
      name: 'Weighted Roll-Up',
      equipment: ['dumbbells'],
      primaryMuscle: 'core',
      movementPattern: 'core',
      difficultyTier: 3,
      instructions: 'Perform a roll up holding a light dumbbell overhead. The weight increases the challenge on the way up and adds control on the way down.',
      easierSubstitution: 'roll_up',
    },
    {
      id: 'db_teaser',
      name: 'Dumbbell Teaser',
      equipment: ['dumbbells'],
      primaryMuscle: 'core',
      secondaryMuscles: ['quads'],
      movementPattern: 'core',
      difficultyTier: 4,
      instructions: 'Lie flat holding a dumbbell. Roll up to a V-sit position with legs lifted and arms extended overhead. Lower back down with control.',
      easierSubstitution: 'weighted_roll_up',
    },
    {
      id: 'weighted_leg_circles',
      name: 'Weighted Leg Circles',
      equipment: ['dumbbells'],
      primaryMuscle: 'core',
      secondaryMuscles: ['quads', 'glutes'],
      movementPattern: 'core',
      difficultyTier: 3,
      instructions: 'Perform leg circles while holding a dumbbell on your chest or between ankles for added resistance. Keep hips stable throughout.',
      easierSubstitution: 'leg_circles',
    },
    {
      id: 'db_side_plank_reach',
      name: 'Dumbbell Side Plank Reach',
      equipment: ['dumbbells'],
      primaryMuscle: 'core',
      secondaryMuscles: ['shoulders'],
      movementPattern: 'core',
      difficultyTier: 3,
      instructions: 'Hold side plank with a dumbbell in top hand. Reach the weight under your body then rotate and extend it toward the ceiling.',
      easierSubstitution: 'side_plank',
    },
    {
      id: 'weighted_bird_dog',
      name: 'Weighted Bird Dog',
      equipment: ['dumbbells'],
      primaryMuscle: 'core',
      secondaryMuscles: ['back', 'glutes'],
      movementPattern: 'core',
      difficultyTier: 3,
      instructions: 'On all fours, hold a dumbbell in one hand. Extend opposite arm and leg simultaneously, keeping hips level. Return with control and switch sides.',
    },
    {
      id: 'weighted_side_kick',
      name: 'Weighted Side Kick Series',
      equipment: ['dumbbells'],
      primaryMuscle: 'glutes',
      secondaryMuscles: ['core', 'quads'],
      movementPattern: 'legs',
      difficultyTier: 3,
      instructions: 'Perform the side kick series with a light dumbbell resting on your outer thigh or held at your hip for added resistance.',
      easierSubstitution: 'side_kick_series',
    },
  ];
}
